---
dependencies:
  - common
  - supervisor
  - edxapp_common
  - nltk
  - role: edx_themes
    theme_users:
      - "{{ edxapp_user }}"
    when: "{{ EDXAPP_ENABLE_COMPREHENSIVE_THEMING }}"
  - role: openstack
    when: "{{ EDXAPP_USE_SWIFT_STORAGE }}"
